### ISSUE TITLE
🐛 [BUG] e3nn 0.3.5 may not be compatible with nequip 0.5.5

### ISSUE THREAD

**Issue by emilannevelink** [mir-group/nequip#236] opened 2022-08-01 17:25 UTC
**Describe the bug**
I just upgraded from nequip 0.5.3 to 0.5.5 and found that I was getting an error in `torch.einsum` in `e3nn.o3.Linear`.

Here is the error message
```
Traceback (most recent call last):
  File "/Users/emil/anaconda3/envs/nequip/lib/python3.9/site-packages/nequip/utils/auto_init.py", line 241, in instantiate
    instance = builder(**positional_args, **final_optional_args)
  File "/Users/emil/anaconda3/envs/nequip/lib/python3.9/site-packages/nequip/nn/_atomwise.py", line 50, in __init__
    self.linear = Linear(
  File "/Users/emil/anaconda3/envs/nequip/lib/python3.9/site-packages/e3nn/o3/_linear.py", line 178, in __init__
    graphmod, self.weight_numel, self.bias_numel = _codegen_linear(
  File "/Users/emil/anaconda3/envs/nequip/lib/python3.9/site-packages/e3nn/o3/_linear.py", line 416, in _codegen_linear
    ein_out = torch.einsum(f"{z}uw,zui->zwi", w, x_list[ins.i_in])
  File "/Users/emil/anaconda3/envs/nequip/lib/python3.9/site-packages/torch/functional.py", line 351, in einsum
    return handle_torch_function(einsum, operands, equation, *operands)
  File "/Users/emil/anaconda3/envs/nequip/lib/python3.9/site-packages/torch/overrides.py", line 1498, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "/Users/emil/anaconda3/envs/nequip/lib/python3.9/site-packages/torch/fx/proxy.py", line 309, in __torch_function__
    raise RuntimeError(f'Found multiple different tracers {list(tracers.keys())} while '
RuntimeError: Found multiple different tracers [<torch.fx.proxy.GraphAppendingTracer object at 0x7fb4de421a60>, <torch.fx.proxy.GraphAppendingTracer object at 0x7fb4de421850>] while trying to trace operations <function einsum at 0x7fb4da671040>
```

**To Reproduce**
initializing a model should throw the error

`model = nequip.model.model_from_config`

**Expected behavior**
No error

**Comment by Linux-cpp-lisp** [comment] 2022-08-02 05:09
This looks like a historical `e3nn` / `opt_einsum_fx` bug, see: https://github.com/e3nn/e3nn/issues/311 that intersects with the PyTorch version you have.  In general I think `nequip` 0.5.5 is still compatible with `e3nn` 0.3.5, but only when `e3nn` 0.3.5 is compatible with the installed PyTorch version.

In general, unless you are trying to recreate a previous environment for reproducing a result, I would recommend just having NequIP and e3nn at the latest current stable versions, along with PyTorch 1.11. (We haven't really tested 1.12 yet.)

**Comment by Linux-cpp-lisp** [comment] 2023-02-20 18:36
This should be resolved with the above comment, just noting that at present our recommending PyTorch versions are 1.11 and 1.13;  1.12 is broken due to upstream PyTorch bugs.

**Closed by Linux-cpp-lisp** 2023-02-20 18:36 UTC
Labels: bug
