### ISSUE TITLE
🐛 [BUG] Segfault with float64 models

### ISSUE THREAD

**Issue by mkphuthi** [mir-group/nequip#255] opened 2022-10-11 20:58 UTC
**Describe the bug**
Nequip models always segfault at prediction time when trained to float64 precision in ASE or LAMMPS on GPU and CPU

**To Reproduce**
```
calc = NequIP(...)
atoms = bulk(...)
calc.get_potential_energy(atoms)
```

Terminal output
```
/home/mphuthi_andrew_cmu_edu/miniconda3/envs/nequip/lib/python3.9/site-packages/nequip/utils/_global_options.py:58: UserWarning: Setting the GLOBAL value for jit fusion strategy to `[('DYNAMIC', 3)]` which is different than the previous value of `[('STATIC', 2), ('DYNAMIC', 10)]`
  warnings.warn(
/home/mphuthi_andrew_cmu_edu/miniconda3/envs/nequip/lib/python3.9/site-packages/nequip/ase/nequip_calculator.py:73: UserWarning: Trying to use chemical symbols as NequIP type names; this may not be correct for your model! To avoid this warning, please provide `species_to_type_name` explicitly.
  warnings.warn(
Segmentation fault
```

**Expected behavior**
No segfault

**Environment (please complete the following information):**
 - OS: CentOS
 - python version: 3.9.0
 - python environment (commands are given for python interpreter):
   - nequip version: 0.5.6
   - e3nn version: 0.5.0
   - pytorch version: 1.11.0
 - (if relevant) GPU support with CUDA
   -  cuda Version according to nvcc: 11.3
   -  cuda version according to PyTorch: 11.3

**Additional context**
I have never been able to get float64 models to work even with other build recipes in the past and with Allegro but they train fine.

**Comment by Linux-cpp-lisp** [comment] 2022-10-13 03:37
Hi @mkphuthi ,

In ASE this is unexpected... I don't get a segfault when trained with `default_dtype: float64` added to `minimal.yaml` and then running:
```
In [1]: from nequip.ase import NequIPCalculator

In [3]: calc = NequIPCalculator.from_deployed_model("test.pth", "cuda")
/home/a/Documents/NequIP/code/nequip/nequip/utils/_global_options.py:45: UserWarning: Setting the GLOBAL value for allow_tf32 to False which is different than the previous value of True
  warnings.warn(
/home/a/Documents/NequIP/code/nequip/nequip/utils/_global_options.py:58: UserWarning: Setting the GLOBAL value for jit fusion strategy to `[('DYNAMIC', 3)]` which is different than the previous value of `[('STATIC', 2), ('DYNAMIC', 10)]`
  warnings.warn(
/home/a/Documents/NequIP/code/nequip/nequip/ase/nequip_calculator.py:73: UserWarning: Trying to use chemical symbols as NequIP type names; this may not be correct for your model! To avoid this warning, please provide `species_to_type_name` explicitly.
  warnings.warn(

In [4]: import ase.build

In [6]: atoms = ase.build.molecule("CH3CHO")

In [7]: atoms.calc = calc

In [8]: atoms.get_potential_energy()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
...
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
...
RuntimeError: expected scalar type Float but found Double


In [9]: import torch

In [10]: torch.set_default_dtype(torch.float64)

In [12]: atoms.get_potential_energy()
Out[12]: -135216.08807821615
```

This could be called a bug (maybe it should detect automatically and convert to float64, or at least try to set the global `set_default_dtype` like the other global settings), but it certainly isn't a segfault... is this only one particular installation / environment where this occurs, or you've reproduced it in multiple places / ways?

In LAMMPS this is currently expected since we at present only support `float32` inputs into the model...

**Comment by mkphuthi** [comment] 2022-10-13 12:16
Setting the default dtype to float64 fixed it! The segfault has been there with every NequIP install I have tried so far. Strange.

**Comment by Linux-cpp-lisp** [comment] 2022-10-13 16:10
Weird... this should error out normally but at that point I'd attribute the problem to PyTorch. Is this all on the same machine, or across machines too that you see this?

Either way, glad that it is resolved. Can I close the issue then for the segfault?

**Comment by mkphuthi** [comment] 2022-10-14 16:25
Yes. I think we can close this issue

**Closed** 2022-10-14 18:21 UTC
Labels: bug
